include: ./analysis_options_flutter_3.13.9.yaml

analyzer:
  language:
    strict-inference: true
  errors:
    invalid_assignment: error
    missing_return: error
    dead_code: error
    todo: error
    # allow deprecated members (we do this because otherwise we have to annotate
    # every member in every test, assert, etc, when we or the Dart SDK deprecates
    # something (https://github.com/flutter/flutter/issues/143312)
    deprecated_member_use: ignore
    deprecated_member_use_from_same_package: ignore
  exclude: # DIFFERENT FROM FLUTTER/FLUTTER
    # Ignore generated files
    - '**/*.g.dart'
    - '**/*.gr.dart'
    - '**/*.freezed.dart'
    - '**/generated_*.dart'

# linter:
#   rules:
#     # analysis_options_flutter_3.13.9.yaml
#     - avoid_setters_without_getters: false
